include ../makefile.d

OBJECTS_NAME := $(wildcard $(OBJECTS_DIR)/*.o)

test: release test_config.exe test_charset.exe test_log.exe

release:
	@if [ ! -d $(TEST_RELEASE_DIR) ]; then mkdir $(TEST_RELEASE_DIR); fi
	@cp config.ini $(TEST_RELEASE_DIR)

# 定义一个规则用于所有 .exe 文件的生成
%.exe: %.cc $(OBJECTS_NAME)
	@$(CC) $(CPPFLAGS) $(INCLUDES) $(OBJECTS) $< -o $(TEST_RELEASE_DIR)/$@ $(OBJECTS_NAME)
